name: PHP Deploy Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Remote SSH to Execution Commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 1. สร้างโฟลเดอร์ในบ้านตัวเอง (ไม่ต้องใช้ sudo สิทธิ์ผ่านฉลุยแน่นอน)
            mkdir -p ~/aphiwat20
            cd ~/aphiwat20

            # 2. ตรวจสอบและดึงโค้ดลงมา
            if [ ! -d ".git" ]; then
              git clone https://github.com/aomsin131263-sketch/aphiwat20.git .
            else
              git fetch origin
              git reset --hard origin/main
            fi
